DATA SEGMENT
    TABLE DB 0*0, 1*1, 2*2, 3*3, 4*4, 5*5, 6*6, 7*7, 8*8, 9*9
DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE, DS:DATA
START:
    MOV AX, 0080H
    MOV DS, AX ; SET DS
    MOV AH, 0
    INT 31H ; SW -> DX
    MOV AL, 00000011B
    INT 32H ; ENABLE DIG
    ; MOV DX, 9 ; DEBUG
    CMP DX, 10
    JB NEXT
    MOV DX, 0
NEXT:
    MOV BX, OFFSET TABLE
    MOV AL, DL
    XLAT
    MOV DL, AL
    MOV AH, 1
    INT 32H ; DISPLAY
    JMP START
CODE ENDS
END START
