CODE SEGMENT PARA 'CODE'
    ASSUME CS:CODE
START:
    XOR DX, DX ; OUTPUT
DISPLAY:
    MOV AH, 0
    MOV AL, 1111B
    INT 32H ; ENABLE DIGITS
    MOV AH, 1
    INT 32H ; DISPLAY DX
    ; READBUTTON
    MOV AH, 0
    INT 33H
    SUB AL, 10000B
    ; IF AVAILABLE
    CMP AL, 10
    JAE DISPLAY ; NO
    ; YES
    ; END IF
    ; IF ALREADY 4 DIGITS
    CMP DX, 0FFFH
    JA CLEAR ; YES
    ; NO
    ; END IF
    MOV CL, 4
    SHL DX, CL
    OR DL, AL
    JMP DISPLAY
CLEAR:
    XOR DX, DX
    OR DL, AL
    JMP DISPLAY
CODE ENDS
END START
